export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const CHANGE_PROD_ID = 'CHANGE_PROD_ID';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REPLACE_ITEM_PRICE = 'REPLACE_ITEM_PRICE';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const INCR_QTY_OF_CART_ITEM = 'INCR_QTY_OF_CART_ITEM';
export const DECR_QTY_OF_CART_ITEM = 'DECR_QTY_OF_CART_ITEM';
export const CHANGE_ATTRIBUTE = 'CHANGE_ATTRIBUTE';
export const GET_TOTAL_COUNT = 'GET_TOTAL_COUNT';
export const SHOW_CURRENCY_SELECT = 'SHOW_CURRENCY_SELECT';
export const SHOW_BAG_SELECT = 'SHOW_BAG_SELECT';
export const GET_QTY_ITEMS_IN_CART = 'GET_QTY_ITEMS_IN_CART';

